export const ITEMS_REQUEST = 'ITEMS_REQUEST';
export const ITEMS_RESOLVE = 'ITEMS_RESOLVE';
export const ITEMS_REJECT  = 'ITEMS_REJECT';

export const CREATE_ITEMS_RESOLVE = 'CREATE_ITEMS_RESOLVE';
export const CREATE_ITEMS_REJECT  = 'CREATE_ITEMS_REJECT';

export const UPDATE_ITEMS_RESOLVE = 'UPDATE_ITEMS_RESOLVE';
export const UPDATE_ITEMS_REJECT  = 'UPDATE_ITEMS_REJECT';

export const REMOVE_ITEMS_RESOLVE = 'REMOVE_ITEMS_RESOLVE';
export const REMOVE_ITEMS_REJECT  = 'REMOVE_ITEMS_REJECT';